import type { BattleSession } from '@/types'

const MOCK_SOLUTION_MARKDOWN_A = [
  '## 思路',
  '',
  '使用 **双指针**：数组已按非递减排序时，从**最左（最小）**与**最右（最大）**同时向中间收拢，可在 **O(n)** 内找到两数之和。',
  '',
  '### 步骤',
  '',
  '1. 令 `left = 0`，`right = nums.length - 1`。',
  '2. 记 `sum = nums[left] + nums[right]`：',
  '   - 若 `sum === target`，返回 `[left, right]`；',
  '   - 若 `sum < target`，需要和更大 → `left++`；',
  '   - 否则 `right--`。',
  '3. 若指针交错仍无解，返回 `[]`。',
  '',
  '### 复杂度',
  '',
  '| 项目 | 复杂度 |',
  '| --- | --- |',
  '| 时间 | **O(n)** |',
  '| 额外空间 | **O(1)** |',
  '',
  '核心循环：',
  '',
  '```javascript',
  'while (left < right) {',
  '  const sum = nums[left] + nums[right];',
  '  if (sum === target) return [left, right];',
  '  sum < target ? left++ : right--;',
  '}',
  '```',
].join('\n')

const MOCK_SOLUTION_MARKDOWN_B = [
  '## 思路',
  '',
  '使用 **哈希表**（`Map`）在一次扫描中记录「值 → 下标」，对每个元素查找 **补数** `target - nums[i]` 是否已出现。',
  '',
  '### 步骤',
  '',
  '1. 创建空 `Map`。',
  '2. 遍历下标 `i`：',
  '   - `need = target - nums[i]`；',
  '   - 若 `map.has(need)`，返回 `[map.get(need), i]`；',
  '   - 否则 `map.set(nums[i], i)`。',
  '3. 遍历结束无解则返回 `[]`。',
  '',
  '### 复杂度',
  '',
  '| 项目 | 复杂度 |',
  '| --- | --- |',
  '| 时间 | **O(n)** |',
  '| 额外空间 | **O(n)**（哈希表） |',
  '',
  '典型写法：',
  '',
  '```javascript',
  'const map = new Map();',
  'for (let i = 0; i < nums.length; i++) {',
  '  const need = target - nums[i];',
  '  if (map.has(need)) return [map.get(need), i];',
  '  map.set(nums[i], i);',
  '}',
  '```',
].join('\n')

/** 未开战时的示例对战：结构与线上一致，官方用例在本机实跑，不写死结果。 */
export function buildMockBattle(problemId: string): BattleSession {
  return {
    id: 'mock-battle',
    problemId: problemId || '1',
    modelAId: '',
    modelBId: '',
    status: 'awaiting_client',
    createdAt: '',
    completedAt: '',
    modelAResult: {
      modelId: 'mock-a',
      status: 'running',
      phase: 'awaiting_execution',
      thought: MOCK_SOLUTION_MARKDOWN_A,
      codingThought: '',
      code: 'function main(nums, target) {\n  let left = 0, right = nums.length - 1;\n  while (left < right) {\n    const sum = nums[left] + nums[right];\n    if (sum === target) return [left, right];\n    sum < target ? left++ : right--;\n  }\n  return [];\n}',
      selfTestCases: [
        { input: '[2,7,11,15], 9', expectedOutput: '[0,1]' },
        { input: '[3,2,4], 6', expectedOutput: '[1,2]' },
      ],
      selfTestConclusion: '自测通过',
      analysisTimeMs: 72,
      codingTimeMs: 48,
      timeMs: 120,
    },
    modelBResult: {
      modelId: 'mock-b',
      status: 'running',
      phase: 'awaiting_execution',
      thought: MOCK_SOLUTION_MARKDOWN_B,
      codingThought: '',
      code: 'function main(nums, target) {\n  const map = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const complement = target - nums[i];\n    if (map.has(complement)) return [map.get(complement), i];\n    map.set(nums[i], i);\n  }\n  return [];\n}',
      selfTestCases: [
        { input: '[2,7,11,15], 9', expectedOutput: '[0,1]' },
        { input: '[3,2,4], 6', expectedOutput: '[1,2]' },
      ],
      selfTestConclusion: '自测通过',
      analysisTimeMs: 55,
      codingTimeMs: 40,
      timeMs: 95,
    },
  }
}
